// typeship — generated smoke tests for the MCP server (dist/mcp.js over stdio).
// Generated by typeship — https://typeship.dev
import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { startMock } from "./helper.mjs";

const server = join(dirname(fileURLToPath(import.meta.url)), "..", "dist", "mcp.js");
const META = {
  "io.modelcontextprotocol/protocolVersion": "2026-07-28",
  "io.modelcontextprotocol/clientCapabilities": {},
  "io.modelcontextprotocol/clientInfo": { name: "typeship-tests", version: "0" },
};

/** Send JSON-RPC requests over stdio and collect the responses by id. */
function talk(env, requests) {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [server], { env: { ...process.env, ...env }, stdio: ["pipe", "pipe", "pipe"] });
    const responses = new Map();
    let buffer = "";
    let stderr = "";
    child.stderr.on("data", (chunk) => (stderr += chunk));
    child.stdout.on("data", (chunk) => {
      buffer += chunk;
      let index;
      while ((index = buffer.indexOf("\n")) !== -1) {
        const line = buffer.slice(0, index).trim();
        buffer = buffer.slice(index + 1);
        if (!line) continue;
        const message = JSON.parse(line);
        responses.set(message.id, message);
        if (responses.size === requests.length) { child.kill(); resolve(responses); }
      }
    });
    child.on("error", reject);
    child.on("exit", () => reject(new Error("mcp server exited before answering: " + stderr)));
    for (const request of requests) child.stdin.write(JSON.stringify(request) + "\n");
  });
}

test("server/discover, tools/list, tools/call over stdio", async () => {
  const mock = await startMock({ status: 201, contentType: "application/json", body: "{\"id\":\"prj_4f8k2m7x9q1v6b3n\",\"object\":\"project\",\"name\":\"example\",\"spec_id\":\"spec_2p8m4q7k1v9d6h3c\",\"auto_generate\":true,\"config\":{\"globals\":[\"example\"],\"retries\":{\"max_retries\":1,\"statuses\":[1],\"initial_delay_ms\":1,\"max_delay_ms\":1,\"retry_non_idempotent\":true,\"disabled\":true,\"operations\":{}},\"pagination\":{},\"auth\":{\"oauth_server\":{\"issuer\":\"https://example.com\",\"discovery_url\":\"https://example.com\",\"authorization_url\":\"https://example.com\",\"token_url\":\"https://example.com\",\"device_authorization_url\":\"https://example.com\",\"scopes\":[\"S123\"],\"audience\":\"example\",\"resource\":\"https://example.com\"},\"oauth_applications\":{},\"oauth_application\":\"example\",\"identity_verification\":{\"subject_field\":\"/id\",\"account_field\":\"/account_id\",\"organization_field\":\"/organization_id\"},\"approval_url\":\"https://example.com\",\"environments\":{}},\"cli\":{\"command_name\":\"example\",\"update_notice\":true,\"changelog_url\":\"example\",\"support_url\":\"example\",\"mcp_url\":\"example\",\"skills_repo\":\"example\"},\"mcp\":{\"registry_name\":\"example\",\"access\":{\"issuer\":\"https://example.com\",\"resource\":\"https://example.com\",\"jwks_url\":\"https://example.com\",\"scopes\":[\"example\"]},\"tool_mode\":\"auto\",\"instructions\":\"example\",\"tool_descriptions\":{},\"reference_resolvers\":{}},\"readme\":{\"quickstart_operation\":\"example\"},\"package\":{\"homepage\":\"example\",\"license\":\"example\",\"license_text\":\"example\",\"copyright\":\"example\",\"go_package_name\":\"example\"},\"docs_url\":\"https://example.com\",\"docs_index_url\":\"https://example.com\"},\"created_at\":\"2024-01-01T00:00:00Z\",\"updated_at\":\"2024-01-01T00:00:00Z\",\"request_id\":\"req_3k8m1v6q9p2d7h4c\"}" });
  try {
    const responses = await talk({ "TYPESHIP_BASE_URL": mock.url, "TYPESHIP_CREDENTIALS": "{\"apiKey\":\"test-token\"}" }, [
      { jsonrpc: "2.0", id: 1, method: "server/discover", params: { _meta: META } },
      { jsonrpc: "2.0", id: 2, method: "tools/list", params: { _meta: META } },
      { jsonrpc: "2.0", id: 3, method: "tools/call", params: { name: "execute", arguments: {"operation":"projects_create","arguments":{"name":"example","spec":{},"targets":[{}]}}, _meta: META } },
    ]);
    const discover = responses.get(1);
    assert.equal(discover.result.supportedVersions[0], "2026-07-28", JSON.stringify(discover));
    const list = responses.get(2);
    assert.ok(list.result.tools.some((tool) => tool.name === "execute"), JSON.stringify(list).slice(0, 200));
    const call = responses.get(3);
    assert.equal(call.result.isError, false, JSON.stringify(call).slice(0, 300));
    assert.equal(call.result.resultType, "complete");
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/projects");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});

test("tool errors prefer the JSON request_id over a stale header", async () => {
  const mock = await startMock({ status: 500, contentType: "application/json", body: JSON.stringify({ code: "internal_error", message: "expected failure", request_id: "req_mcp_body_test" }), headers: { "Request-Id": "req_mcp_stale" } });
  try {
    const responses = await talk({ "TYPESHIP_BASE_URL": mock.url, "TYPESHIP_CREDENTIALS": "{\"apiKey\":\"test-token\"}" }, [
      { jsonrpc: "2.0", id: 4, method: "tools/call", params: { name: "execute", arguments: {"operation":"projects_create","arguments":{"name":"example","spec":{},"targets":[{}]}}, _meta: META } },
    ]);
    const call = responses.get(4);
    assert.equal(call.result.isError, true, JSON.stringify(call).slice(0, 300));
    const detail = JSON.parse(call.result.content[0].text);
    assert.equal(detail.request_id, "req_mcp_body_test");
  } finally {
    mock.close();
  }
});
