/**
 * Result projection shared by the generated CLI (--fields) and MCP server
 * (the fields argument). Generated by Typeship — https://typeship.dev
 */

/** Keep only `paths` of a value: arrays item by item, objects by dotted
 * path, including paths through arrays (`items.id` keeps each item's id);
 * scalars untouched. */
export function projectFields(value: unknown, paths: string[][] | null): unknown {
  if (paths === null) return value;
  if (Array.isArray(value)) return value.map((v) => projectFields(v, paths));
  if (value === null || typeof value !== "object") return value;
  const groups = new Map<string, string[][]>();
  for (const [key, ...rest] of paths) {
    if (key === undefined) continue;
    const group = groups.get(key);
    if (group) group.push(rest); else groups.set(key, [rest]);
  }
  const out: Record<string, unknown> = {};
  for (const [key, rests] of groups) {
    const child = (value as Record<string, unknown>)[key];
    if (child === undefined) continue;
    if (rests.some((rest) => rest.length === 0)) out[key] = child;
    else if (child !== null && typeof child === "object") out[key] = projectFields(child, rests);
  }
  return out;
}

/** A requested path that selected nothing, with the keys that exist where
 * it stopped matching. */
export interface UnmatchedField {
  path: string;
  /** Keys present at the level where the path failed, first 40. */
  available: string[];
  /** The path segment that is not a key there, or null when the path runs
   * into a scalar or the result is not an object. */
  missing: string | null;
}

/**
 * The paths that match nothing in any item of `value`. A path matches when
 * at least one item has it; reaching null or an empty array counts as a
 * match, because the path may be right and the values merely empty. An
 * empty result matches everything.
 */
export function unmatchedFields(value: unknown, paths: string[][]): UnmatchedField[] {
  const out: UnmatchedField[] = [];
  for (const path of paths) {
    const miss = { depth: -1, keys: new Set<string>(), segment: null as string | null };
    if (!pathMatches(value, path, 0, miss)) {
      out.push({ path: path.join("."), available: [...miss.keys].slice(0, 40), missing: miss.segment });
    }
  }
  return out;
}

function pathMatches(value: unknown, path: string[], index: number, miss: { depth: number; keys: Set<string>; segment: string | null }): boolean {
  if (value === null || value === undefined) return true;
  if (Array.isArray(value)) {
    if (value.length === 0) return true;
    let any = false;
    for (const item of value) if (pathMatches(item, path, index, miss)) any = true;
    return any;
  }
  if (index === path.length) return true;
  if (typeof value !== "object") {
    if (miss.depth < index) { miss.depth = index; miss.keys = new Set(); miss.segment = null; }
    return false;
  }
  const key = path[index]!;
  const record = value as Record<string, unknown>;
  if (!Object.hasOwn(record, key)) {
    if (miss.depth < index) { miss.depth = index; miss.keys = new Set(); miss.segment = key; }
    if (miss.depth === index) for (const k of Object.keys(record)) miss.keys.add(k);
    return false;
  }
  return pathMatches(record[key], path, index + 1, miss);
}

/** The error message: the call went through, and for each unmatched path,
 * what exists instead. */
export function unmatchedFieldsMessage(unmatched: UnmatchedField[], perItem: boolean): string {
  return "The API call succeeded, but " + unmatched.map((u, index) => {
    const where = perItem ? " in any item" : " in the result";
    const why = u.missing !== null
      ? " (\"" + u.missing + "\" is not a key there)"
      : " (it runs into a value that is not an object)";
    const keys = u.available.length > 0 ? " Available keys: " + u.available.join(", ") + "." : "";
    return (index === 0 ? "the" : "The") + " field path \"" + u.path + "\" matched nothing" + where + why + "." + keys;
  }).join(" ");
}
