#!/usr/bin/env node
// typeship — MCP server. Generated by typeship — https://typeship.dev
// Speaks MCP 2026-07-28 (stateless: per-request _meta, server/discover; no
// initialize handshake, no sessions); the protocol layer and tool surface
// live in ./mcp-protocol.js, shared with typeship's hosted endpoint. Two
// transports, zero dependencies:
//   node mcp.js            stdio (newline-delimited JSON-RPC 2.0)
//   createMcpHandler()    configured Streamable HTTP handler
// Surface switches (flags or environment):
//   --read-only / TYPESHIP_MCP_READ_ONLY=1     reads only; writes are not callable
//   --tools a,b / TYPESHIP_MCP_TOOLS=a,b       only these resources or tools
//   TYPESHIP_MCP_MAX_RESULT_CHARS=<n>          result size cap (default 64000)
// The bare handleHttp()/--http entry stays closed until a handler is configured.
// HTTP validates a dedicated MCP token and resolves API credentials through
// createMcpHandler's application-owned callback; stdio resolves auth from the
// environment, then from credentials/config saved by the CLI's `login`
// and `config` commands (same files, so one login covers both bins).

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { TypeshipClient, formatDebugEvent, type ClientOptions, type DebugEvent } from "./index.js";
import { GLOBALS, OMITTED_OPS, OPS, buildArgs, type OpSpec } from "./ops.js";
import {
  DEFAULT_MAX_RESULT_CHARS, SUPPORTED_PROTOCOL_VERSIONS, McpAccountLinkRequired, argumentsError, asJsonRpc, binaryOutcome, callSharedTool, checkRequestHeaders,
  dataOutcome, errorOutcome, handleRpc, isRpcOutcome, pageOutcome, parseIncludeList, prepareCall, resolveReferences, serverInstructions,
  takeCancelled, textError, toolDefinitions, visibleOps,
  type ArgumentIssue, type DocsSource, type McpServer, type OpLike, type RpcOutcome, type ToolOutcome,
} from "./mcp-protocol.js";
import { fetchDocsText } from "./docs.js";
import { assertCredentialDestination, assertStoredIdentity, oauthSessionToken } from "./oauth-session.js";
import { createCredentialStore } from "./credential-storage.js";
import { identityPolicyOf, verifyClientIdentity, type IdentityConfiguration } from "./api-identity.js";
import { parseNamedCredentials, resolveNamedCredentials, namedCredentialAvailability, type NamedCredentials, type CredentialSchemes } from "./named-credentials.js";
import { resolveProfile, profileFlag, readProfileConfig } from "./auth-profiles.js";
import { createMcpAuthorizer, McpAuthorizationError, type McpAuthorizationConfiguration, type McpTokenIntrospectionConfiguration, type McpPrincipal } from "./mcp-authorization.js";
export type { McpAuthorizationConfiguration, McpTokenIntrospectionConfiguration, McpPrincipal } from "./mcp-authorization.js";
export { McpAccountLinkRequired } from "./mcp-protocol.js";

const BIN = "typeship";
const PKG_NAME = "@typeship-ax/mcp";
const SERVER_NAME = "typeship-mcp";
const SERVER_VERSION = "0.13.0";
/** The MCP client's announced name (clientInfo in request _meta), for the User-Agent. */
let MCP_CLIENT_NAME: string | null = null;
function noteClientInfo(message: unknown): void {
  const meta = (message as { params?: { _meta?: Record<string, { name?: unknown }> } } | null)?.params?._meta;
  const name = meta?.["io.modelcontextprotocol/clientInfo"]?.name;
  if (typeof name === "string" && name && name !== MCP_CLIENT_NAME) { MCP_CLIENT_NAME = name.slice(0, 60); }
}
const DEFAULT_BASE_URL = "https://typeship.dev/api/v1";
const NAMED_SCHEMES: CredentialSchemes = {"apiKey":{"kind":"bearer","options":["bearerToken"]}};
const AUTH_SCALARS: { option: string; flag: string; env: string }[] = [{"option":"bearerToken","flag":"token","env":"TYPESHIP_TOKEN"}];
const BASIC: { envUser: string; envPass: string } | null = null;

const ENVIRONMENTS: Record<string, string> = {};
const DOCS_URL_DEFAULT: string | null = "https://typeship.dev";
const DOCS_INDEX_URL_DEFAULT: string | null = null;
/** "meta" collapses per-operation tools into search/read/execute so huge
 * APIs don't flood agent context with hundreds of tools. */
const TOOL_MODE: "operations" | "meta" = "meta";
/** Project-supplied guidance appended to the server instructions. */
const CUSTOM_INSTRUCTIONS: string | null = null;
/** The tool that returns the caller (the CLI's whoami target), named in the instructions. */
const IDENTITY_TOOL: string | null = "account_retrieve";
/** Surface switches: reads only, and/or a subset of resources or tools.
 * Flags win over the environment. */
const ARGV = process.argv.slice(2);
const READ_ONLY = ARGV.includes("--read-only") || process.env["TYPESHIP_MCP_READ_ONLY"] === "1" || process.env["TYPESHIP_MCP_READ_ONLY"] === "true";
const INCLUDE = parseIncludeList(ARGV.includes("--tools") ? ARGV[ARGV.indexOf("--tools") + 1] : process.env["TYPESHIP_MCP_TOOLS"]);
const MAX_RESULT_CHARS = Number(process.env["TYPESHIP_MCP_MAX_RESULT_CHARS"]) || DEFAULT_MAX_RESULT_CHARS;
/** One sentence on where credentials come from on each transport; goes
 * into the instructions and into 401 results. */
const AUTH_HINT_STDIO = "Credentials come from the MCP server's environment (TYPESHIP_CREDENTIALS, TYPESHIP_TOKEN) or from 'typeship login'";
const AUTH_HINT_HTTP = "Sign in to this MCP server. The server resolves your API credentials separately; its connection token is never forwarded to the API.";
/** The tool list is fixed at generation, so clients may cache it for an
 * hour and shared caches may hold it (identical for every caller). */
const TOOLS_TTL_MS = 60 * 60 * 1000;

function configRoot(): string {
  return join(process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config"), BIN);
}

function configDir(): string { return resolveProfile(configRoot(), { flag: profileFlag(ARGV), environment: process.env["TYPESHIP_PROFILE"] }).directory; }

function readJson<T>(file: string): T | null {
  if (!LOCAL_CREDENTIALS) return null;
  try {
    return JSON.parse(readFileSync(join(configDir(), file), "utf8")) as T;
  } catch {
    return null;
  }
}

function makeClient(op: OpSpec): TypeshipClient {
  const profile = LOCAL_CREDENTIALS ? resolveProfile(configRoot(), { flag: profileFlag(ARGV), environment: process.env["TYPESHIP_PROFILE"] }) : null;
  const store = createCredentialStore(profile?.directory ?? configRoot(), process.env["TYPESHIP_CREDENTIAL_STORE"], "TYPESHIP_CREDENTIAL_STORE");
  if (BASIC && (process.env[BASIC.envUser] !== undefined) !== (process.env[BASIC.envPass] !== undefined)) throw new Error("Supply both Basic-auth environment variables together, or use a complete named Basic credential.");
  const envNamed = LOCAL_CREDENTIALS && process.env["TYPESHIP_CREDENTIALS"] !== undefined ? parseNamedCredentials(process.env["TYPESHIP_CREDENTIALS"], NAMED_SCHEMES) : {};
  const explicitOptions = new Set(AUTH_SCALARS.filter((a) => process.env[a.env] !== undefined).map((a) => a.option));
  if (BASIC && process.env[BASIC.envUser] !== undefined && process.env[BASIC.envPass] !== undefined) explicitOptions.add("basicAuth");

  namedCredentialAvailability(NAMED_SCHEMES, explicitOptions, envNamed);
  const identityPolicy = {};
  const identityOp = OPS.find((candidate) => candidate.tool === IDENTITY_TOOL);
  const identity: IdentityConfiguration | undefined = identityOp && Object.keys(identityPolicy).length ? { operation: identityOp.resource + "." + identityOp.method, fields: identityPolicy } : undefined;
  const explicitCredentials = op.credentialOptions?.some((alternative) => alternative.length > 0 && alternative.every((option) => explicitOptions.has(option)));
  const stored = op.auth !== "none" && LOCAL_CREDENTIALS && !explicitCredentials ? store.read() : null;
  const config = profile ? readProfileConfig(profile.directory) : {};
  const baseUrl = process.env["TYPESHIP_BASE_URL"]
    ?? config?.baseUrl
    ?? (config?.environment !== undefined ? ENVIRONMENTS[config.environment] : undefined)
    ?? DEFAULT_BASE_URL ?? undefined;
  if (baseUrl === undefined) {
    // Thrown, not exited: the agent gets an isError result naming the fix
    // instead of a server that vanished mid-conversation.
    throw new Error("No base URL configured: set TYPESHIP_BASE_URL in the MCP server's environment, or run '" + BIN + " config set base-url <url>'.");
  }
  if (stored) { assertCredentialDestination(stored, { apiBaseUrl: baseUrl, environment: config.environment, profile: profile?.name }); assertStoredIdentity(stored, identity); }
  const options: ClientOptions & Record<string, unknown> = { baseUrl };
  for (const a of AUTH_SCALARS) {
    const v = process.env[a.env] ?? stored?.scalars?.[a.option];
    if (v !== undefined) options[a.option] = v;
  }
  if (BASIC) {
    const username = process.env[BASIC.envUser] ?? stored?.basic?.username;
    const password = process.env[BASIC.envPass] ?? stored?.basic?.password;
    if (username !== undefined && password !== undefined) options.basicAuth = { username, password };
  }
  const envOptions: Record<string, unknown> = {};
  for (const a of AUTH_SCALARS) if (process.env[a.env] !== undefined) envOptions[a.option] = process.env[a.env];
  if (BASIC && process.env[BASIC.envUser] !== undefined && process.env[BASIC.envPass] !== undefined) envOptions.basicAuth = { username: process.env[BASIC.envUser], password: process.env[BASIC.envPass] };
  options.credentials = resolveNamedCredentials(NAMED_SCHEMES, [
    { named: stored?.named, options: { ...stored?.scalars, ...(stored?.basic ? { basicAuth: stored.basic } : {}) } },
    { named: envNamed, options: envOptions },
  ]);


  for (const g of GLOBALS) {
    const value = process.env["TYPESHIP_" + g.envSuffix];
    if (value !== undefined) options[g.option] = value;
  }
  if (process.env["TYPESHIP_DEBUG"] === "1") {
    options.debug = (event: DebugEvent) => process.stderr.write(formatDebugEvent(BIN + "-mcp", event) + "\n");
  }
  // The local MCP server identifies itself (surface + the client it serves, when announced).
  options.defaultHeaders = { "User-Agent": PKG_NAME + "-mcp/" + SERVER_VERSION + " (typeship" + (MCP_CLIENT_NAME ? "; client=" + MCP_CLIENT_NAME : "") + ")" };
  // Keep the SDK's machine-token cache while re-evaluating local configuration.
  const key = createHash("sha256").update(JSON.stringify([options, config, profile?.name, stored?.oauth?.sessionId, null, process.env["TYPESHIP_DEBUG"]])).digest("hex");
  if (clientInstance && clientKey === key) return clientInstance;
  const client = new TypeshipClient(options);
  clientKey = key;
  CLIENT_CREDENTIALS.set(client, Object.keys(options.credentials ?? {}).length > 0 || AUTH_SCALARS.some((a) => options[a.option] !== undefined) || options.basicAuth !== undefined || options.bearerToken !== undefined || options.clientCredentials !== undefined);
  return (clientInstance = client);
}

let clientInstance: TypeshipClient | undefined;
let clientKey = "";
const CLIENT_CREDENTIALS = new WeakMap<TypeshipClient, boolean>();

/** Resolve configuration and credentials for each tool call, including login/logout changes. */
function getClient(op: OpSpec): TypeshipClient {
  return makeClient(op);
}

/** Run one operation through the generated SDK: the same client, the same
 * typed errors and pagination a hand-written caller would get. */
async function callOperationRaw(op: OpSpec, rawArgs: Record<string, unknown>, remote: RemoteContext | undefined, client: TypeshipClient): Promise<ToolOutcome> {
  // Arguments are checked against the tool's schema first: unknown names,
  // wrong types and missing requirements come back as one isError result,
  // nothing reaches the API half-formed and nothing is dropped silently.
  const prepared = prepareCall(op as unknown as OpLike, rawArgs, { maxChars: MAX_RESULT_CHARS });
  if (!prepared.ok) return prepared.outcome;
  const { args, fields, maxChars } = prepared.call;
  const values: Record<string, unknown> = {};
  for (const p of op.params) {
    if (args[p.name] !== undefined) values[p.name] = args[p.name];
  }
  // File arguments are local paths on this machine; unreadable ones are
  // argument errors, reported before anything is sent.
  const fileIssues: ArgumentIssue[] = [];
  let rawBody: unknown = op.bodyStyle === "data" ? args.body : undefined;
  if (LOCAL_PROCESS && !remote) {
    for (const p of op.params) {
      if (p.type !== "file" || typeof values[p.name] !== "string") continue;
      try { values[p.name] = fileArgument(values[p.name] as string); } catch (e) { fileIssues.push({ code: "INVALID_ARGUMENT", argument: p.name, message: p.name + ": cannot read " + String(values[p.name]) + " (" + (e as Error).message + ")" }); }
    }
    if (op.bodyKind === "binary" && typeof rawBody === "string") {
      try { rawBody = fileArgument(rawBody); } catch (e) { fileIssues.push({ code: "INVALID_ARGUMENT", argument: "body", message: "body: cannot read " + String(rawBody) + " (" + (e as Error).message + ")" }); }
    }
  }
  if (fileIssues.length > 0) return argumentsError(op, fileIssues);
  const callArgs = buildArgs(
    op,
    values,
    rawBody,
    typeof args.select === "string" ? args.select : undefined,
  );
  const errorContext = {
    authHint: remote ? AUTH_HINT_HTTP : AUTH_HINT_STDIO,
    docsUrl: docsSource.docsUrl(),
    hadCredential: !!remote || CLIENT_CREDENTIALS.get(client) === true,
  };
  const shape = { fields, maxChars, pagination: op.pagination, args };
  try {
    const target = (client as unknown as Record<string, Record<string, (...a: unknown[]) => unknown>>)[op.resource]!;
    const result = await (target[op.method]!(...callArgs) as Promise<{ ok: boolean; data?: unknown; error?: unknown; response?: { requestId?: string } }>);
    if (!result.ok) return errorOutcome(result.error, errorContext);
    if (op.paginated) {
      const page = result.data as { items: unknown[]; nextPageParams(): Record<string, unknown> | null; response: { requestId?: string } };
      return pageOutcome(page.items, page.nextPageParams(), { ...shape, requestId: page.response.requestId });
    }
    // A binary body (the SDK hands back a Blob): an image block, or a file
    // on disk, never "{}".
    if (result.data instanceof Blob) return binaryOutcome(result.data, { tool: op.tool, ...(LOCAL_PROCESS && !remote ? { saveBinary } : {}) });
    return dataOutcome(result.data, shape);
  } catch (e) {
    return textError((e as Error).message ?? "Tool call failed");
  }
}

/** Name-or-ID resolution is the one wrapper around the ordinary executor,
 * so a direct operation tool and compact execute take exactly the same path. */
const REFERENCE_CACHES = new Map<string, Map<string, string | number>>();
function referenceCacheFor(authHeader?: string): Map<string, string | number> {
  const key = createHash("sha256").update(JSON.stringify([authHeader ?? "stdio", clientKey])).digest("hex");
  let cache = REFERENCE_CACHES.get(key);
  if (!cache) {
    cache = new Map();
    REFERENCE_CACHES.set(key, cache);
    while (REFERENCE_CACHES.size > 16) REFERENCE_CACHES.delete(REFERENCE_CACHES.keys().next().value!);
  }
  return cache;
}

async function callOperation(op: OpSpec, rawArgs: Record<string, unknown>, remote?: RemoteContext): Promise<ToolOutcome> {
  const prepared = prepareCall(op as unknown as OpLike, rawArgs, { maxChars: MAX_RESULT_CHARS });
  if (!prepared.ok) return prepared.outcome;
  // One client/session for the entire tool, including name-to-ID lookups.
  // If login changes during a lookup, the token callback rejects the old session.
  let client: TypeshipClient;
  try { client = remote ? await remote.client() : getClient(op); } catch (error) {
    if (remote && error instanceof McpAccountLinkRequired) throw error;
    return textError(remote ? "API access is unavailable for this MCP account. Reconnect your API account or contact the server owner." : (error as Error).message);
  }
  const resolved = await resolveReferences(op as unknown as OpLike, prepared.call.args, {
    ops: OPS as unknown as OpLike[],
    identityTool: IDENTITY_TOOL,
    cache: remote?.references ?? referenceCacheFor(),
    runOperation: (source, args) => callOperationRaw(source as OpSpec, args, remote, client),
  });
  if (!resolved.ok) return resolved.outcome;
  const args = {
    ...resolved.args,
    ...(prepared.call.fields ? { fields: prepared.call.fields.map((path) => path.join(".")) } : {}),
  };
  return callOperationRaw(op, args, remote, client);
}

/** Running as a process on this machine (stdio, or --http launched here),
 * as opposed to imported by a worker: the server can read and write local
 * files, so uploads are tools and binaries are saved to disk. */
const LOCAL_PROCESS = invokedDirectly();
/** Saved human sessions are available only to local stdio, never HTTP/worker callers. */
const LOCAL_CREDENTIALS = LOCAL_PROCESS && !ARGV.includes("--http");
/** The callable operations: event streams are CLI-only, uploads are tools
 * only on a local server (mcpExposed), writes are out under --read-only,
 * and --tools narrows to a subset. A hidden operation is unknown to
 * tools/call and execute alike. */
const MCP_OPS = visibleOps(OPS as unknown as OpLike[], { readOnly: READ_ONLY, include: INCLUDE, uploads: LOCAL_PROCESS }) as unknown as OpSpec[];
const HIDDEN_WRITES = READ_ONLY ? visibleOps(OPS as unknown as OpLike[], { include: INCLUDE, uploads: LOCAL_PROCESS }).length - MCP_OPS.length : 0;
const HAS_UPLOADS = MCP_OPS.some((op) => op.bodyKind === "multipart" || op.bodyKind === "binary");

/** A local file as an upload part (multipart field or raw body). */
function fileArgument(path: string): File {
  return new File([readFileSync(path)], basename(path));
}

/** Where binary responses land on a local server: a per-server temp dir. */
function saveBinary(bytes: Uint8Array, _mediaType: string, suggestedName: string): string {
  const dir = join(tmpdir(), SERVER_NAME);
  mkdirSync(dir, { recursive: true });
  const path = join(dir, Date.now().toString(36) + "-" + suggestedName);
  writeFileSync(path, bytes);
  return path;
}

const docsSource: DocsSource = {
  ops: MCP_OPS as unknown as OpLike[],
  omittedOps: OMITTED_OPS as unknown as OpLike[],
  generatedOperationCount: OPS.length,
  docsUrl: () => readJson<{ docsUrl?: string }>("config.json")?.docsUrl ?? DOCS_URL_DEFAULT,
  docsIndexUrl: () => readJson<{ docsUrl?: string }>("config.json")?.docsUrl ? null : DOCS_INDEX_URL_DEFAULT,
  fetchText: fetchDocsText,
};

/** One validated remote identity and API client per HTTP request. */
interface RemoteContext { client(): Promise<TypeshipClient>; references: Map<string, string | number> }

function serverFor(remote?: RemoteContext): McpServer {
  const operations = remote ? visibleOps(MCP_OPS as unknown as OpLike[], { uploads: false }) : MCP_OPS as unknown as OpLike[];
  const source = remote ? { ...docsSource, ops: operations } : docsSource;
  const website = docsSource.docsUrl();
  return {
    serverInfo: { name: SERVER_NAME, title: "typeship", version: SERVER_VERSION, ...(website ? { websiteUrl: website } : {}) },
    instructions: serverInstructions({
      title: "typeship",
      ops: operations,
      toolCount: operations.length,
      generatedOperationCount: OPS.length,
      omittedOps: docsSource.omittedOps,
      mode: TOOL_MODE,
      readOnly: READ_ONLY,
      hiddenWrites: HIDDEN_WRITES,
      authHint: remote ? AUTH_HINT_HTTP : AUTH_HINT_STDIO,
      identityTool: MCP_OPS.some((o) => o.tool === IDENTITY_TOOL) ? IDENTITY_TOOL : null,
      referenceResolution: MCP_OPS.some((o) => o.params.some((p) => p.resolve && typeof p.resolve === "object")),
      uploads: !remote && HAS_UPLOADS,
      custom: CUSTOM_INSTRUCTIONS,
    }),
    toolsTtlMs: TOOLS_TTL_MS,
    listTools: () => toolDefinitions(source.ops, TOOL_MODE, source.omittedOps),
    unknownToolMessage: TOOL_MODE === "meta"
      ? (name) => "Unknown tool: " + name + ". This server uses compact mode; call search_docs to discover an operation, then call execute with operation: \"" + name + "\"."
      : undefined,
    callTool: async (name, args) => {
      const shared = await callSharedTool(name, args, source, (op, opArgs) => callOperation(op as OpSpec, opArgs, remote));
      if (shared !== undefined) return shared;
      // tools/list is the callable contract. In meta mode every operation
      // goes through execute, including its destructive-operation
      // confirmation gate; an unlisted operation name must stay unknown.
      if (TOOL_MODE !== "operations") return undefined;
      const op = operations.find((o) => o.tool === name);
      return op ? callOperation(op as OpSpec, args, remote) : undefined;
    },
  };
}

// ---- Streamable HTTP transport ---------------------------------------------

/** Origins allowed to call the HTTP transport from a browser. Non-browser
 * MCP clients send no Origin and are always accepted; the spec requires
 * validating the header when present (DNS-rebinding defense), so browser
 * callers must be same-host, localhost, or listed in
 * TYPESHIP_MCP_ALLOWED_ORIGINS (comma-separated, "*" for any). */
function originAllowed(request: Request, resourceOrigin: string): boolean {
  const origin = request.headers.get("origin");
  if (origin === null) return true;
  const allowed = (process.env["TYPESHIP_MCP_ALLOWED_ORIGINS"] ?? "").split(",").map((s) => s.trim()).filter(Boolean);
  if (allowed.includes("*") || allowed.includes(origin)) return true;
  try {
    const o = new URL(origin);
    if (o.origin === resourceOrigin) return true;
    return ["localhost", "127.0.0.1", "[::1]"].includes(new URL(resourceOrigin).hostname) && ["localhost", "127.0.0.1", "[::1]"].includes(o.hostname);
  } catch {
    return false;
  }
}

function corsHeaders(request: Request): Record<string, string> {
  return {
    "Access-Control-Allow-Origin": request.headers.get("origin") ?? "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Expose-Headers": "WWW-Authenticate",
    "Access-Control-Allow-Headers": "Content-Type, Authorization, Accept, MCP-Protocol-Version, Mcp-Method, Mcp-Name",
    Vary: "Origin",
  };
}

export interface McpHttpOptions {
  authorization?: McpAuthorizationConfiguration;
  /** Optional server-only introspection. When set, checks every token with the
   * provider instead of local JWT verification. Never put secrets in config. */
  introspection?: McpTokenIntrospectionConfiguration;
  /** Application-owned lookup or token exchange for this verified identity.
   * Keep it outside the generated directory so regeneration preserves it.
   * Throw McpAccountLinkRequired with a public linking page when the user
   * needs to connect an account. Always verify the link server-side on retry.
   * The MCP access token and request headers are deliberately not provided. */
  credentialsFor(principal: McpPrincipal): ClientOptions | Promise<ClientOptions>;
}

/** Create once at startup; metadata/key caching is isolated to this server. */
export function createMcpHandler(options: McpHttpOptions): (request: Request) => Promise<Response> {
  const configured = {} as { mcpIssuer?: string | null; mcpResource?: string | null; mcpJwksUrl?: string | null; mcpScopes?: string[] | null };
  const apiBaseUrl = process.env["TYPESHIP_BASE_URL"] ?? DEFAULT_BASE_URL ?? undefined;
  const authorizer = createMcpAuthorizer(options.authorization ?? { issuer: configured.mcpIssuer ?? "", resource: configured.mcpResource ?? "", ...(configured.mcpJwksUrl ? { jwksUrl: configured.mcpJwksUrl } : {}), scopes: configured.mcpScopes ?? [] }, options.introspection);
  if (typeof options.credentialsFor !== "function") throw new Error("Provide credentialsFor to resolve each MCP caller's upstream API credentials.");
  return (request) => authorizedHttp(request, authorizer, options.credentialsFor, apiBaseUrl).catch(() => new Response(JSON.stringify({ error: "MCP request failed." }), { status: 500, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } }));
}

/** A generated entry point cannot infer the host application's user-to-API
 * credential mapping. It remains closed until the owner installs a handler. */
export async function handleHttp(_request: Request): Promise<Response> {
  return new Response(JSON.stringify({ error: "Configure createMcpHandler with MCP authorization and credentialsFor before serving remote requests." }), { status: 503, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } });
}

async function authorizedHttp(request: Request, authorizer: ReturnType<typeof createMcpAuthorizer>, credentialsFor: McpHttpOptions["credentialsFor"], apiBaseUrl: string | undefined): Promise<Response> {
  const url = new URL(request.url);
  const resource = new URL(authorizer.configuration.resource);
  const cors = originAllowed(request, resource.origin) ? corsHeaders(request) : {};
  const json = (status: number, body: unknown, extra: Record<string, string> = {}) =>
    new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json", "Cache-Control": "no-store", ...extra } });

  if (request.method === "OPTIONS") {
    return new Response(null, { status: originAllowed(request, resource.origin) ? 204 : 403, headers: cors });
  }
  if (!originAllowed(request, resource.origin)) {
    return json(403, { jsonrpc: "2.0", error: { code: -32600, message: "Origin not allowed. Set TYPESHIP_MCP_ALLOWED_ORIGINS to permit browser callers." } });
  }
  const metadataPath = "/.well-known/oauth-protected-resource" + resource.pathname.replace(/\/$/, "");
  if (url.pathname === metadataPath && request.method === "GET") return json(200, authorizer.metadata());
  if (url.pathname !== resource.pathname) return json(404, { error: "Unknown MCP endpoint." });
  if (request.method !== "POST") {
    // GET streams, DELETE (session end) and Mcp-Session-Id belong to earlier
    // revisions; the spec asks modern-only servers to answer 405.
    return json(405, { error: "POST JSON-RPC messages to this endpoint (MCP " + SUPPORTED_PROTOCOL_VERSIONS[0] + ", stateless)." }, { Allow: "POST, OPTIONS" });
  }

  let principal: McpPrincipal;
  try { principal = await authorizer.authorize(request.headers.get("authorization")); }
  catch (error) {
    const failure = error instanceof McpAuthorizationError ? error : new McpAuthorizationError(503, "authorization_unavailable");
    return json(failure.status, { error: failure.code, message: failure.message }, failure.status === 503 ? {} : { "WWW-Authenticate": authorizer.challenge(failure.code === "insufficient_scope" ? "insufficient_scope" : "invalid_token") });
  }
  let client: Promise<TypeshipClient> | undefined;
  const remote: RemoteContext = { references: new Map(), client: () => client ??= (async () => {
    const credentials = await credentialsFor(principal);
    if (!credentials || typeof credentials !== "object") throw new Error("API credentials unavailable.");
    const baseUrl = apiBaseUrl;
    if (typeof baseUrl !== "string") throw new Error("Configure the upstream API URL.");
    if (credentials.baseUrl !== undefined && credentials.baseUrl !== baseUrl) throw new Error("API credentials target a different API URL.");
    const token = request.headers.get("authorization")!.slice(7);
    const transport = credentials.fetch ?? fetch;
    return new TypeshipClient({ ...credentials, baseUrl, fetch: async (input, init) => {
      const headers = new Headers(init?.headers);
      const destination = new URL(typeof input === "string" ? input : input instanceof URL ? input.href : input.url);
      if ([...headers.values()].some(value => value === token || value === "Bearer " + token) || [...destination.searchParams.values()].includes(token)) throw new Error("An MCP connection token cannot authorize an upstream API request.");
      return transport(input, init);
    } });
  })() };

  let incoming: unknown;
  try {
    incoming = await request.json();
  } catch {
    return json(400, { jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } });
  }
  const parsed = asJsonRpc(incoming);
  if (isRpcOutcome(parsed)) return json(parsed.status, parsed.message);
  // Header/body agreement is checked for requests; the spec defines no
  // header requirements for notification POSTs.
  if (parsed.id !== undefined && parsed.id !== null && parsed.method !== "initialize") {
    const mismatch = checkRequestHeaders(request.headers, parsed);
    if (mismatch) return json(mismatch.status, mismatch.message);
  }
  noteClientInfo(parsed);
  let outcome: RpcOutcome;
  try {
    outcome = await handleRpc(serverFor(remote), parsed);
  } catch (e) {
    return json(500, { jsonrpc: "2.0", id: parsed.id ?? null, error: { code: -32603, message: "Internal error" } });
  }
  if (outcome.message === null) {
    return new Response(null, { status: outcome.status, headers: cors });
  }
  return json(outcome.status, outcome.message);
}

function startHttp(port: number): void {
  void import("node:http").then(({ createServer }) => {
    createServer((req, res) => {
      let body = "";
      req.on("data", (chunk) => (body += chunk));
      req.on("end", () => {
        void handleHttp(
          new Request("http://localhost:" + port + (req.url ?? "/"), {
            method: req.method,
            headers: Object.fromEntries(
              Object.entries(req.headers).map(([k, v]) => [k, Array.isArray(v) ? v.join(", ") : String(v ?? "")]),
            ),
            ...(req.method === "POST" ? { body } : {}),
          }),
        ).then(async (response) => {
          res.statusCode = response.status;
          response.headers.forEach((value, key) => res.setHeader(key, value));
          res.end(await response.text());
        }).catch((e: unknown) => {
          // handleHttp never rejects; this guards the Request construction
          // and socket writes so one bad connection can't take the server.
          process.stderr.write(SERVER_NAME + ": " + ((e as Error).message ?? String(e)) + "\n");
          if (!res.headersSent) res.statusCode = 500;
          res.end();
        });
      });
    }).listen(port, () => {
      process.stderr.write(SERVER_NAME + " listening on http://localhost:" + port + "\n");
    });
  });
}

// ---- stdio transport --------------------------------------------------------

async function startStdio(): Promise<void> {
  // dynamic: node:readline doesn't exist in worker runtimes, and workers
  // never take the stdio path
  const { createInterface } = await import("node:readline");
  const rl = createInterface({ input: process.stdin });
  const write = (message: Record<string, unknown>) => process.stdout.write(JSON.stringify(message) + "\n");
  const server = serverFor();
  rl.on("line", (line) => {
    const trimmed = line.trim();
    if (trimmed === "") return;
    let incoming: unknown;
    try {
      incoming = JSON.parse(trimmed);
    } catch {
      write({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } });
      return;
    }
    const id = incoming !== null && typeof incoming === "object" && !Array.isArray(incoming) ? (incoming as { id?: unknown }).id : undefined;
    noteClientInfo(incoming);
    void handleRpc(server, incoming)
      .then((outcome) => {
        if (outcome.message === null) return;
        // A cancelled request gets no response (spec: MUST NOT send further messages).
        if (takeCancelled(id)) return;
        write(outcome.message);
      })
      .catch((e) => {
        if (id !== undefined) {
          write({ jsonrpc: "2.0", id: id ?? null, error: { code: -32603, message: "Internal error" } });
        }
      });
  });
  // Spec: exit promptly when stdin closes.
  rl.on("close", () => process.exit(0));
}

/** True when this file is the process entry: `node dist/mcp.js`, the
 * package's `typeship-mcp` bin (a symlink, so compare real paths), or
 * `npx tsx src/mcp.ts`. False when imported (worker.ts, tests). */
function invokedDirectly(): boolean {
  const entry = process.argv[1];
  if (typeof entry !== "string" || entry === "") return false;
  try {
    return realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return /mcp\.(js|mjs|ts)$/.test(entry);
  }
}
if (invokedDirectly()) {
  const httpFlag = process.argv.indexOf("--http");
  if (httpFlag !== -1) {
    const port = Number(process.argv[httpFlag + 1]) || Number(process.env.PORT) || 3000;
    startHttp(port);
  } else {
    void startStdio();
  }
}
