// typeship — host this MCP server on Cloudflare.
// Generated by typeship — https://typeship.dev
// Before deployment, create an application-owned Worker entry using
// createMcpHandler from this package with credentialsFor for each verified
// MCP identity. Set wrangler.toml main to that entry. The generated default
// stays closed; ambient API credentials cannot authorize remote callers.
import { handleHttp } from "./mcp.js";

export default {
  fetch(request: Request): Promise<Response> {
    return handleHttp(request);
  },
};
